### ISSUE TITLE
Domain Cookie Invalid for Localhost:8080

### ISSUE THREAD

**Issue by KenticoDevTrev** [KenticoDevTrev/PartialWidgetPage#10]
The following error occurs when running lcoalhost:8080 and using PartialWidgetPage with stripSessions: false

Line 36:    Line 37:       <header>   Line 38:           @Html.PartialWidgetPage("/Masterpage/Header", PathIsNodeAliasPath:   true, stripSession: false)   Line   39:           @{OutputCacheHelper.AddCacheDependency($"nodes\|{OutputCacheHelper.CurrentSiteName()}\|Generic.Header\|all");   }   Line 40:
--

**Comment by jknopp** [comment]
@KenticoDevTrev I ran into this issue also while running the Baseline project (thanks for releasing that!), and have created PR #11 to address the issue. Thoughts?

**Comment by jknopp** [comment]
@KenticoDevTrev after reading the documentation again I noticed it says, 'setting this to the empty string ("") will restrict the port to the one used in the HTTP response'. So potentially localhost doesn't need to be handled differently and Port = "" could always be set regardless. Do you see any reason the port would need to be set explicitly?

**Comment by KenticoDevTrev** [comment]
I don't think page builder would need a specific port, unless the admin and the actual mvc site were both localhost... Do you want to do any other testing, otherwise I'll pull and give it a check what you committed in the pull request

**Comment by jknopp** [comment]
@KenticoDevTrev just ran a few more tests and added 1 other bug fix, everything seems to load for me as expected now, ready for you to take a swing when you can.

**Comment by KenticoDevTrev** [comment]
Thanks, I'll try to get to it soon so you can update your nuget package.
Appreciate you contributing!

**Comment by KenticoDevTrev** [comment]
Pulled the Pull Request, Updated in nuget package 12.29.5 (should be available for update shortly).

Thanks again!
