### ISSUE TITLE
NodeAliasPathToUrl Cache Dependency

### ISSUE THREAD

**Issue by jknopp** [KenticoDevTrev/PartialWidgetPage#13]
For this cache dependency:
https://github.com/KenticoDevTrev/PartialWidgetPage/blob/master/PartialWidgetPage/PartialWidgetPageExtensions.cs#L167

Shouldn't it be one of these? 
- `documentid|<document id>`
- `nodeid|<node id>`

I can't get `cms.document|byid|<document id>` to fire, and I don't see it listed here: https://docs.kentico.com/k12sp/configuring-kentico/configuring-caching/setting-cache-dependencies

My thought was that saving the partial Page in the Admin would clear that dependent key, but it doesn't seem to. Maybe I am missing something?

**Comment by KenticoDevTrev** [comment]
Good catch, looks like i blanked out when adding the dependencies, sorry it took a while to see this one.  I'll work on getting it fixed and pushed.

**Comment by KenticoDevTrev** [comment]
Will be available shortly in the nuget package to update.  Fixed in #2028f39a404622a32ec6aa21b20de690c06affb8

**Comment by jknopp** [comment]
Awesome! I have updated my solution with the new package, and thanks for the note, I will keep that in mind as I add new PartialWidgetPages as well.
