### ISSUE TITLE
Typo: "Parital" Widget Rendering

### ISSUE THREAD

**Issue by ChristopherBass** [KenticoDevTrev/PartialWidgetPage#32]
https://github.com/KenticoDevTrev/PartialWidgetPage/blob/master/K13Core/PartialWidgetPage.Kentico.MVC.Core/ParitalWidgetRendering.cs  
The code works fine, just noting the typo in the class name and file as defined. 
:-D

**Comment by KenticoDevTrev** [comment]
Finally resolved in the Xperience by Kentico verison.
