### ISSUE TITLE
Wrong encoding of content in partial widget pages

### ISSUE THREAD

**Issue by rkeitel** [KenticoDevTrev/PartialWidgetPage#5]
Characters - like ä, ö, ü, ß in German - are displayed as "ÃƒÂ¶" or something else. If I show the same content in a normal widget, which is not added to a partial widget page, the characters are correctly encoded.

**Comment by KenticoDevTrev** [comment]
Sorry i honestly totally missed there were issues in this repo! I"ll see about these when i can do a round of bug fixes

**Comment by KenticoDevTrev** [comment]
I'm having a hard time replicating, so maybe this is already resolve in a later version.  When i added ä, ö, ü, ß to my header page that is pulled in with the partial widget page, it showed properly:

![image](https://user-images.githubusercontent.com/47198675/84686628-f0eb4500-af01-11ea-9431-23892749c48b.png)


![image](https://user-images.githubusercontent.com/47198675/84686605-e466ec80-af01-11ea-8dd1-714e3fcd5cfc.png)
