### ISSUE TITLE
Using of Page instead of Path in PartialWidgetPageModel

### ISSUE THREAD

**Issue by rkeitel** [KenticoDevTrev/PartialWidgetPage#6]
Instead of using the path, the page should be used, because the paths could be changed by adapting the page alias, which leads to broken links:
```
[EditingComponent(PageSelector.IDENTIFIER, Label = "Page", Order = 0, Tooltip = "The page to render, the URL will be determined by the page type's URL pattern")]
public IList<PageSelectorItem> Page { get; set; }
```

**Comment by KenticoDevTrev** [comment]
I created a separate branch for your pull request, and have published it on Nuget as https://www.nuget.org/packages/RKeitel.PartialWidgetPage.Kentico.MVC it should be installable at some point.  If you need to make further changes, you can fork that branch and make your own adjustments to tweak it to your liking and run the BuildPackage.bat (after updating the assembly version).
