### ISSUE TITLE
ActualUrl in PartialWidgetPageModel doesn't respect ApplicationPath

### ISSUE THREAD

**Issue by rkeitel** [KenticoDevTrev/PartialWidgetPage#7]
If the site is running on localhost in a specific application path, this one is not included in the returned ActualUrl, so the partial widget page cannot be resolved. Currently I have overridden the the url in the getter of ActualUrl:
```
var url = PartialWidgetPageExtensions.NodeAliasPathToUrl(document?.NodeAliasPath)
    .Replace("~//", "~/")
    .Replace("~", $"~{HttpContext.Current.Request.ApplicationPath}");
```

**Comment by KenticoDevTrev** [comment]
This has been resolved now on 12.29.7 with proper virtual directory context handling and resolving of ~ for paths (both the relative URL of the NodeAliasPath and also ~ in url paths)
