### ISSUE TITLE
ActualUrl in PartialWidgetPageModel returns URL with wrong culture code

### ISSUE THREAD

**Issue by rkeitel** [KenticoDevTrev/PartialWidgetPage#8]
On my site, there are three supported languages: English US (default), English UK and German. In the page application of Kentico there are a lot of pages, which only have a default version, because the translation of the content is either not necessary or resolved by localization macros.
The URL returned by ActualUrl always includes "en-US" instead of the current culture code.
At the moment, I have overridden the getter of ActualUrl:
```
var cultureCode = HttpContext.Current.Request.RequestContext.RouteData.Values["culture"]?.ToString();
if (cultureCode != null)
{
    var culture = new CultureInfo(cultureCode);
    url = Regex.Replace(url, LocalizationContext.CurrentCulture.CultureCode, culture.Name, RegexOptions.IgnoreCase);
}
```
`LocalizationContext.CurrentCulture.CultureCode` is always "en-US" in my case.

**Comment by KenticoDevTrev** [comment]
With this one, are you setting the System Culture?  You usually need to set that somehow for the LocalizationContext.CurrentCulture.CultureCode to work.

      CultureInfo.CurrentCulture = CultureInfo.CreateSpecificCulture("nl-NL");

**Comment by rkeitel** [comment]
Yes, when I check the CurrentCulture before accessing the ActualUrl then CurrentCulture is "de-DE", but in the ActualUrl it is "en-US".

**Comment by KenticoDevTrev** [comment]
What is the difference in the url between German and English? Do you have
the culture in the url or are you setting it some other way?

Dynamic routing should, if configured right, create url slugs for each
language variation and should set the current language to the right one.

**Comment by rkeitel** [comment]
I have the culture in the URL, like https://localhost/de-DE/... I don't use your dynamic routing system for resolving the URLs. A route handler is setting the CurrentCulture by accessing an URL with culture code.

**Comment by KenticoDevTrev** [comment]
As you can see from
https://github.com/KenticoDevTrev/PartialWidgetPage/blob/master/PartialWidgetPage/PartialWidgetPageExtensions.cs

All I do is call either the url passed, or get the url from the node
itself, so you have a misconfiguration in either how that url is retrieved
or how mvc handles the request.

What is the exact partial widget page you are calling and what is the url
pattern for that page type in Kentico?

**Comment by rkeitel** [comment]
The problem is that LocalizationContext.CurrentCulture.CultureCode always returns en-US although Thread.CurrentThread.CurrentCulture is de-DE. I followed the instructions on https://devnet.kentico.com/questions/how-to-get-culture-code-of-current-request, and the problem exists only in PartialWidgetPages. Normal pages work as expected.

The URL pattern for the partial widget page type is "/{%DocumentCulture%}/Components/EmployeeHighlight/{%NodeGUID%}"

**Comment by KenticoDevTrev** [comment]
Are you following Kentico direction to set the UI culture once you receive
the request? Documentation seems to be down but you should be setting the
thread current culture on your first pages request, so when the partial
widget page gets the partial page url it uses the right culture.

**Comment by rkeitel** [comment]
Yes, I set the (UI) culture like in https://docs.kentico.com/k12sp/multilingual-websites/setting-up-multilingual-mvc-projects.

**Comment by rkeitel** [comment]
Note: There are no culture specific pages in the page tree. All pages are created with the default culture (en-US). By accessing the pages with a different culture their content is localized by resource strings. Because of that LocalizationContext.CurrentCulture.CultureCode seems to be always en-US.

**Comment by KenticoDevTrev** [comment]
That may be the issue then.  The Partial Page widget grabs the full URL of
the page and makes the request, in this case it will be /en-US/... because
the page is only in the english language.

You can instead tell it that it's not a NodeAliasPath and instead generate
the URL yourself with the culture your request is made.  If you
do @Html.PartialWidgetPage("/de-DE/My-Page") it will make that request.
Can you try that?

While i can see the need to overwrite the language, it could be very hard
to accomplish this, you really should localize the pages in the languages
you support, then this issue would largely be resolved.

**Comment by rkeitel** [comment]
As a workaround I currently overwritten the ActualUrl getter and replace the culture in the URL with the correct one from the request (see my first post). But this should be always done, because the Thread.CurrentThread.CurrentCulture is relevant and not the other one. There are many cases where independent culture-specific pages are not necessary, because there aren't editor fields or translation is done by resource strings.

**Comment by KenticoDevTrev** [comment]
Not sure how i would go about accomplishing your request in terms of a full fix.  You will just need to pass it the proper URL path instead of a nodealiaspath in your request, and add the culture in there, that's the only way for it to know where to pull it in in the case where the culture you request isn't found.
